### ISSUE TITLE
restore wallet issues

### ISSUE THREAD

**Issue by boqiu** [Conflux-Chain/conflux-wallet#1]
![image](https://user-images.githubusercontent.com/35757521/55378442-8db70200-554b-11e9-96c6-724f063fc7e5.png)

![image](https://user-images.githubusercontent.com/35757521/55378574-1fbf0a80-554c-11e9-9df3-4c884012f65a.png)

**Comment by jnoodle** [comment]
DONE，现在关闭钱包后是不会记忆用户的密码的，恢复钱包相当于重新设置密码，所以不用输入和之前一样的密码

**Comment by boqiu** [comment]
还有密码长度要求不一致的问题

**Comment by jnoodle** [comment]
我给调整了一下，新建的时候也必须8位以上，要不建不了

![image](https://user-images.githubusercontent.com/1267447/55395948-4fced380-5575-11e9-8a2f-5555d5c25f86.png)
