### ISSUE TITLE
Send Error: the field must have byte length of 20

### ISSUE THREAD

**Issue by justinpan0** [Conflux-Chain/conflux-wallet#13]
This might sound stupid but I tried to call the contract with a specific contract address, but meet with the following error "The field to must have byte length of 20". However, I can call contract without any specified contract address.
![conflux1](https://user-images.githubusercontent.com/1756450/55755067-218d4000-5a1c-11e9-8dc1-67cae744ce46.JPG)
![Capture](https://user-images.githubusercontent.com/1756450/55755103-3b2e8780-5a1c-11e9-8034-5703d168b014.JPG)

**Comment by AngeliaQ** [comment]
From the error message, the "contract address" you input is incorrect, which is not of length 20. when you call contract without any specified contract address, it will deploy the contract

**Comment by justinpan0** [comment]
Thanks, so I have the following questions:
1. 成功deploy后的交易哈希并不是contract address，对吗？那么如何找到已经deploy的contract address？
2. 为什么没有specified contract address的时候就可以deploy？这样不应该报错么？

**Comment by AngeliaQ** [comment]
1. 首先拿到交易哈希后，等一段时间去http://confluxscan.io/ 搜索交易哈希，在地址里能看到
<img width="775" alt="WeChat7554eeda4cb6deca51c2aed990bdfcf9" src="https://user-images.githubusercontent.com/31834656/55774979-fb25de00-5ac9-11e9-8c44-622a05869daa.png">
<img width="1202" alt="WeChataa6607135290ac6b601c3effc6ec1e58" src="https://user-images.githubusercontent.com/31834656/55774990-04af4600-5aca-11e9-8347-b7e8bcfbaffc.png">
<img width="1064" alt="WeChat6814cf26fee85a14f2b4517c0b18889c" src="https://user-images.githubusercontent.com/31834656/55774995-08db6380-5aca-11e9-9528-7bbea34896f4.png">
2.目前分为deploy contract和call contract，如果call contract没有contract address就是deploy contract；后续会继续优化，call contact的时候address必填

**Comment by justinpan0** [comment]
Got it, thanks!
