### ISSUE TITLE
send tx page issues

### ISSUE THREAD

**Issue by boqiu** [Conflux-Chain/conflux-wallet#4]
![image](https://user-images.githubusercontent.com/35757521/55379098-467e4080-554e-11e9-93f1-3dcfb10bef52.png)

![image](https://user-images.githubusercontent.com/35757521/55379210-d3c19500-554e-11e9-8824-da30ea441f3c.png)

**Comment by AngeliaQ** [comment]
Gwei->Gdrip
第二个ui不改

**Comment by jnoodle** [comment]
DONE
