### ISSUE TITLE
homepage issues

### ISSUE THREAD

**Issue by boqiu** [Conflux-Chain/conflux-wallet#5]
![image](https://user-images.githubusercontent.com/35757521/55379308-3a46b300-554f-11e9-8755-b6cf78129208.png)

**Comment by AngeliaQ** [comment]
目前send和deploy都是最后报锁定错误，配置还是能改的，先维持原状

**Comment by jnoodle** [comment]
Faucet 默认是给第一个地址充值

**Comment by boqiu** [comment]
能否从设计上显式的告诉用户给哪个地址充值？

**Comment by jnoodle** [comment]
![image](https://user-images.githubusercontent.com/1267447/55397103-fe741380-5577-11e9-8be3-b8700589c6b3.png)

**Comment by AngeliaQ** [comment]
Done
