### ISSUE TITLE
Best epoch number is not changed

### ISSUE THREAD

**Issue by boqiu** [Conflux-Chain/conflux-wallet#6]
![image](https://user-images.githubusercontent.com/35757521/55526374-756bf200-56c7-11e9-9979-49bf4da39a7a.png)

**Comment by boqiu** [comment]
only occurs in an old test env

**Comment by boqiu** [comment]
remove "best" for "best epoch  number", you can use "latest epoch number" instead.

**Comment by AngeliaQ** [comment]
Done
