### ISSUE TITLE
There is no way to export seed phrase

### ISSUE THREAD

**Issue by charles-lei** [Conflux-Chain/conflux-wallet#79]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
just can get the private key
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
copy the seed phrase generated from private key
**If this is a feature request, what is motivation or use case for changing the behavior?**
I want to get the seed phrase and import it to the wallet of browser extention
**If this is a associated bounty or submission, please add the url to it here.**

**Please mention other relevant information such as the browser version, and Operating System.**

**Comment by AngeliaQ** [comment]
It does not support generating the seed phrase from the private key. You can follow the steps: 

first, generating a seed phrase account in extension wallet(ConfluxPortal); 

second, import the web wallet export JSON data to the extension wallet of the browser extension(ConfluxPortal).

**Comment by yqrashawn** [comment]
Or you can create a new account in ConfluxPortal and transfer cfx and other tokens from your wallet address to Portal address.

**Comment by charles-lei** [comment]
Thanks for all of your information, I will close this issue.
